### PR TITLE
Add custom proposal implementation

### PR DESCRIPTION
**Pull request by tensojka**
Lacks setting of custom proposal configuration during deployment

Please review

### CODE REVIEW

**Comment by tensojka** [comment]
Tests will be added once @Nerrolol finishes and merges the test setup scaffolding

**Comment by Nerrolol** [comment]
lgtm !

**Review by Nerrolol — COMMENTED** [review]
lgtm !

**Review by StarkFishinator — APPROVED** [review]

**Comment by tensojka** [comment]
Rebased on master (master has package and imports renamed from governance to konoha

**Pull request merged**
